[package]
name = "public-api-server-aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.12.10", features = ["json"] }
rocket = { version = "0.5.1", features = ["serde_json"] }
serde = "1.0.216"
serde_json = "1.0.134"
